# Generated by Django 2.0.1 on 2018-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180730_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_one',
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
